// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApu-KlrdK40c38_QU-kBdbZALe0qWDlag',
    appId: '1:73407213102:web:b665a703f28ebf2f6339bf',
    messagingSenderId: '73407213102',
    projectId: 'studentapp-59d34',
    authDomain: 'studentapp-59d34.firebaseapp.com',
    storageBucket: 'studentapp-59d34.firebasestorage.app',
    measurementId: 'G-TYZHY4BDDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6HaLknZ9oqjRkntV-EoC5rkCEdanqicI',
    appId: '1:73407213102:android:f31eb9e47fa622146339bf',
    messagingSenderId: '73407213102',
    projectId: 'studentapp-59d34',
    storageBucket: 'studentapp-59d34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6W-N-anocu6aJd06xEQEloVbqjdKOpeY',
    appId: '1:73407213102:ios:094382041212be0e6339bf',
    messagingSenderId: '73407213102',
    projectId: 'studentapp-59d34',
    storageBucket: 'studentapp-59d34.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6W-N-anocu6aJd06xEQEloVbqjdKOpeY',
    appId: '1:73407213102:ios:094382041212be0e6339bf',
    messagingSenderId: '73407213102',
    projectId: 'studentapp-59d34',
    storageBucket: 'studentapp-59d34.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApu-KlrdK40c38_QU-kBdbZALe0qWDlag',
    appId: '1:73407213102:web:1c17c1312e8ff72e6339bf',
    messagingSenderId: '73407213102',
    projectId: 'studentapp-59d34',
    authDomain: 'studentapp-59d34.firebaseapp.com',
    storageBucket: 'studentapp-59d34.firebasestorage.app',
    measurementId: 'G-97FS09ZP04',
  );
}
